// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package services

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Healthcheck is an autogenerated mock type for the Healthcheck type
type Healthcheck struct {
	mock.Mock
}

// DatabaseReady provides a mock function with given fields:
func (_m *Healthcheck) DatabaseReady() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMemUsage provides a mock function with given fields:
func (_m *Healthcheck) GetMemUsage() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// LastSyncExecution provides a mock function with given fields:
func (_m *Healthcheck) LastSyncExecution() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// OnlineSince provides a mock function with given fields:
func (_m *Healthcheck) OnlineSince() time.Duration {
	ret := _m.Called()

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// SetOnlineSince provides a mock function with given fields: _a0
func (_m *Healthcheck) SetOnlineSince(_a0 time.Time) {
	_m.Called(_a0)
}
