// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package notification

import mock "github.com/stretchr/testify/mock"

// Emailer is an autogenerated mock type for the Emailer type
type Emailer struct {
	mock.Mock
}

// Informations provides a mock function with given fields: to, subject, body
func (_m *Emailer) Informations(to string, subject string, body []byte) {
	_m.Called(to, subject, body)
}

// Send provides a mock function with given fields:
func (_m *Emailer) Send() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
